-- REVISÃO DE ERROS NA TABELA EDITORA

DROP TABLE EDITORA CASCADE;


CREATE  TABLE  EDITORA(
	EDITORAID SERIAL PRIMARY KEY,
	CNPJ 	VARCHAR(20) NOT NULL,
	NOME	VARCHAR(250) NOT NULL,
	CEP 	VARCHAR(20) NOT NULL,
	RUA	VARCHAR(250)NOT NULL,
	NUMERO VARCHAR(30),
	BAIRRO VARCHAR(250) NOT NULL,
	CIDADE VARCHAR(250) NOT NULL,
	UF	   VARCHAR(2) NOT NULL
);








